name: tag_and_deploy

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true

env:
  TERRAFORM_VERSION: 1.1.4

jobs:
  tag_new_version:
    runs-on: ubuntu-20.04
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}
      changelog: ${{ steps.tag_version.outputs.changelog }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform Init
        id: init
        run: terraform init -no-color -lock-timeout=20s
        continue-on-error: true

      - name: Terraform Select Workspace
        run: terraform workspace new ${{ inputs.environment }} || terraform workspace select ${{ inputs.environment }}

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -lock-timeout=20s -out plan.out
        continue-on-error: true

      - name: Terraform apply
        run: terraform apply -auto-approve -no-color -lock-timeout=20s plan.out

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
          create_annotated_tag: true
          custom_release_rules: >
            hotfix:patch:Fix,
            fix:patch:Fix,
            patch:patch:Fix,
            bug:patch:Fix,
            security:patch:Security,
            feat:minor:Feature,
            feature:minor:Feature,
            minor:minor:Feature,
            breaking:major:BREAKING,
            break:major:BREAKING,
            major:major:BREAKING,
            stable:major:BREAKING,
            release:major:BREAKING

      - name: Generate fancy Release name
        id: fancy_name
        run: |
          arr1=(admiring adoring affectionate agitated amazing angry awesome beautiful blissful bold boring brave busy charming clever cool compassionate competent condescending confident cranky crazy dazzling determined distracted dreamy eager ecstatic elastic elated elegant eloquent epic exciting fervent festive flamboyant focused friendly frosty funny gallant gifted goofy gracious great happy hardcore heuristic hopeful hungry infallible inspiring interesting intelligent jolly jovial keen kind laughing loving lucid magical mystifying modest musing naughty nervous nice nifty nostalgic objective optimistic peaceful pedantic pensive practical priceless quirky quizzical recursing relaxed reverent romantic sad serene sharp silly sleepy stoic strange stupefied suspicious sweet tender thirsty trusting unruffled upbeat vibrant vigilant vigorous wizardly wonderful xenodochial youthful zealous zen)
          arr2=(albattani allen almeida antonelli agnesi archimedes ardinghelli aryabhata austin babbage banach banzai bardeen bartik bassi beaver bell benz bhabha bhaskara black blackburn blackwell bohr booth borg bose bouman boyd brahmagupta brattain brown buck burnell cannon carson cartwright carver cerf chandrasekhar chaplygin chatelet chatterjee chebyshev cohen chaum clarke colden cori cray curran curie darwin davinci dewdney dhawan diffie dijkstra dirac driscoll dubinsky easley edison einstein elbakyan elgamal elion ellis engelbart euclid euler faraday feistel fermat fermi feynman franklin gagarin galileo galois ganguly gates gauss germain goldberg goldstine goldwasser golick goodall gould greider grothendieck haibt hamilton haslett hawking hellman heisenberg hermann herschel hertz heyrovsky hodgkin hofstadter hoover hopper hugle hypatia ishizaka jackson jang jemison jennings jepsen johnson joliot jones kalam kapitsa kare keldysh keller kepler khayyam khorana kilby kirch knuth kowalevski lalande lamarr lamport leakey leavitt lederberg lehmann lewin lichterman liskov lovelace lumiere mahavira margulis matsumoto maxwell mayer mccarthy mcclintock mclaren mclean mcnulty mendel mendeleev meitner meninsky merkle mestorf mirzakhani montalcini moore morse murdock moser napier nash neumann newton nightingale nobel noether northcutt noyce panini pare pascal pasteur payne perlman pike poincare poitras proskuriakova ptolemy raman ramanujan ride ritchie rhodes robinson roentgen rosalind rubin saha sammet sanderson satoshi shamir shannon shaw shirley shockley shtern sinoussi snyder solomon spence stonebraker sutherland swanson swartz swirles taussig tereshkova tesla tharp thompson torvalds tu turing varahamihira vaughan visvesvaraya volhard villani wescoff wilbur wiles williams williamson wilson wing wozniak wright wu yalow yonath zhukovsky)
          echo ::set-output name=release_name::"${arr1[RANDOM%${#arr1[@]}]}-${arr2[RANDOM%${#arr2[@]}]}"

      - name: debug
        run: echo ${{ steps.fancy_name.outputs.release_name }}

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: ${{ steps.fancy_name.outputs.release_name }}
          body: ${{ steps.tag_version.outputs.changelog }}



