name: Helm Build and Push

on:
  workflow_call:
    secrets:
      GAR_HELM_REGISTRY_ACCOUNT:
        required: true
      GAR_HELM_REGISTRY_URL:
        required: true

  # push:
  #   paths:
  #     - charts/**
  #   branches:
  #     - "main"

env:
  HELM_VERSION: "3.9.0"

jobs:
  tag_new_version:
    runs-on: ubuntu-20.04
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}
      changelog: ${{ steps.tag_version.outputs.changelog }}
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: '0'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GAR_HELM_REGISTRY_ACCOUNT }}'

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v1.1.0

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ""
          release_branches: main
          create_annotated_tag: true
          custom_release_rules: hotfix:patch:Fix,fix:patch:Fix,patch:patch:Fix,bug:patch:Fix,security:patch:Security,feat:minor:Feature,feature:minor:Feature,minor:minor:Feature,breaking:major:BREAKING,break:major:BREAKING,major:major:BREAKING,stable:major:BREAKING,release:major:BREAKING

      - name: Generate fancy Release name
        id: fancy_name
        run: |
          arr1=(admiring adoring affectionate agitated amazing angry awesome beautiful blissful bold boring brave busy charming clever cool compassionate competent condescending confident cranky crazy dazzling determined distracted dreamy eager ecstatic elastic elated elegant eloquent epic exciting fervent festive flamboyant focused friendly frosty funny gallant gifted goofy gracious great happy hardcore heuristic hopeful hungry infallible inspiring interesting intelligent jolly jovial keen kind laughing loving lucid magical mystifying modest musing naughty nervous nice nifty nostalgic objective optimistic peaceful pedantic pensive practical priceless quirky quizzical recursing relaxed reverent romantic sad serene sharp silly sleepy stoic strange stupefied suspicious sweet tender thirsty trusting unruffled upbeat vibrant vigilant vigorous wizardly wonderful xenodochial youthful zealous zen)
          arr2=(alena alexander andreas anna-barbara anne annika anton arne benjamin bettina birte brian caroline caspar celina christopher claudia cornelia daniel darleen denise elena elisabeth emilia fenja florian gregor grischa hagen hannes holger ingo insa jan jana janine jasmin jasper jochen johannes jörg josefine josephine julia juliane kathrin kim lena-josefin lennart lian lukas maike manon marcus marie marie-christine mario matthias melanie mirjam nadine niclas nicola nils ole peggy peter philip ralf roy sabrina sarah sarina sharlyn sophia stella-sophie steven tobias yvonne )
          echo ::set-output name=release_name::"${arr1[RANDOM%${#arr1[@]}]}-${arr2[RANDOM%${#arr2[@]}]}"

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: ${{ steps.fancy_name.outputs.release_name }}
          body: ${{ steps.tag_version.outputs.changelog }}

      - name: ⚗️ [INSTALL] helm
        uses: azure/setup-helm@v1
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Helm Package
        id: helm-package
        run: for d in ./charts/* ; do helm package --version ${{ steps.tag_version.outputs.new_tag }} "${d}"; done

      - name: Registry Login
        id: registry-login
        run: gcloud auth print-access-token | helm registry login -u oauth2accesstoken --password-stdin https://${{ secrets.GAR_HELM_REGISTRY_URL }}

      - name: Push Chart
        id: helm-push-chart
        run: for c in $(ls ./*.tgz); do helm push $c oci://${{ secrets.GAR_HELM_REGISTRY_URL }}; done