name: Docker Release
on:
  workflow_call:
    inputs:
      PROJECT:
        type: string
        required: true
      GCP_REGISTRY:
        type: string
        required: false
        default: "eu.gcr.io"
      GAR_REGISTRY:
        type: string
        required: false
        default: "europe-west3-docker.pkg.dev"
    secrets:
      GCR_JSON_KEY:
        required: true
      GAR_HELM_REGISTRY_ACCOUNT:
        required: true

jobs:
  docker-release:
    runs-on: ubuntu-22.04
    steps:
      - name: lowercase things
        id: lowercase
        env:
          project: ${{inputs.PROJECT}}

        run: |
          echo "project=${project,,}"  >> "$GITHUB_OUTPUT"

      - name: download a build artifact
        uses: actions/download-artifact@v4.1.4
        id: download
        with:
          name: artifacts_image_${{steps.lowercase.outputs.project}}

      - name: load image
        id: image_ids
        run: |
          {
            echo 'ids<<EOF'
            docker image load --input image_${{steps.lowercase.outputs.project}}.tar | sed 's/Loaded image: //g'
            echo EOF
          } >> $GITHUB_OUTPUT

      - name: login to gcr
        uses: docker/login-action@v3.1.0
        with:
          registry: ${{ inputs.GCP_REGISTRY }}
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}

      - name: login to gar
        uses: docker/login-action@v3.1.0
        with:
          registry: ${{ inputs.GAR_REGISTRY}}
          username: _json_key
          password: ${{ secrets.GAR_HELM_REGISTRY_ACCOUNT }}

      - name: push to registry
        run: |
          TAGS="${{steps.image_ids.outputs.ids}}"
          for tag in ${TAGS}; do
            docker push "${tag}"
          done
