name: Docker Build
on:
  workflow_call:
    inputs:
      PROJECT:
        type: string
        required: true
    secrets:
      SSH_KEY:
        required: false


jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - uses: webfactory/ssh-agent@v0.6.0
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        if: "${{ env.SSH_KEY != ''}}"
        with:
            ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: Build and push
        uses: docker/build-push-action@v3
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        if: "${{ env.SSH_KEY = ''}}"
        with:
          context: .
          push: false
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: image_${{inputs.PROJECT}}:${{github.ref_name}}
      - name: Build and push with ssh
        uses: docker/build-push-action@v3
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        if: "${{ env.SSH_KEY != ''}}"
        with:
          context: .
          push: false
          load: true
          ssh: default
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: image_${{inputs.PROJECT}}:${{github.ref_name}}
      - name: docker image save
        run: docker image save image_${{inputs.PROJECT}}:${{github.ref_name}} -o ./image_${{inputs.PROJECT}}_${{github.ref_name}}.tar
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: artifacts_image_${{github.ref_name}}
          path: ./image_${{inputs.PROJECT}}_${{github.ref_name}}.tar
          retention-days: 1