name: Docker Unittest
on:
  workflow_call:
    inputs:
      FILE:
        type: string
        default: Dockerfile

jobs:
  docker-unittest:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.1

      - name: conftest
        uses: docker://openpolicyagent/conftest:v0.46.0@sha256:7da98fe5e8fe091193769e67a1823bfd1cfd16f682046474ce4ac81c0bd41dce
        with:
          args: test ${{inputs.FILE}} --all-namespaces --no-color
