name: Docker Unittest
on:
  workflow_call:

jobs:
  docker-unittest:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3.5.2

      - name: conftest
        uses: docker://openpolicyagent/conftest:v0.42.1@sha256:da120c6e4d5d274138ebd711fc5e16658e4cb3ccce1ff4979d653ccc3902d1cc
        with:
          args: test Dockerfile --all-namespaces --no-color
