name: Docker Docs
on:
  workflow_call:
    inputs:
      PROJECT:
        type: string
        required: true

jobs:
  docker-docs:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3.5.3

      - name: download a build artifact
        uses: actions/download-artifact@v3.0.2
        id: download
        with:
          name: artifacts_image_${{github.ref_name}}

      - name: docker-docs
        uses: docker://anchore/syft:v0.83.0@sha256:aa3c040294b0a46b5cf38859fc245da929772161431e1003bfe43cb2852d128d
        with:
          args: packages docker-archive:./image_${{inputs.PROJECT}}_${{github.ref_name}}.tar  -o template -t "./README.md.tmpl" > README.md

      - name: commit changes
        uses: EndBug/add-and-commit@v9.1.3
        with:
          default_author: github_actions
          message: 'Update Readme'
          add: 'README.md'
