name: Docker Build
on:
  workflow_call:
    inputs:
      PROJECT:
        type: string
        required: true
    secrets:
      SSH_KEY:
        required: false


jobs:
  docker-build:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0

      - name: set up qemu
        uses: docker/setup-qemu-action@v2.1.0

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2.4.1

      - name: add key to ssh-agent
        uses: webfactory/ssh-agent@v0.7.0
        if: "${{ env.SSH_KEY != ''}}"
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        with:
            ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: build and push
        if: "${{ env.SSH_KEY == ''}}"
        uses: docker/build-push-action@v4.0.0
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        with:
          context: .
          push: false
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: image_${{inputs.PROJECT}}:${{github.ref_name}}

      - name: build and push with ssh
        uses: docker/build-push-action@v4.0.0
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        if: "${{ env.SSH_KEY != ''}}"
        with:
          context: .
          push: false
          load: true
          ssh: default
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: image_${{inputs.PROJECT}}:${{github.ref_name}}

      - name: docker image save
        run: docker image save image_${{inputs.PROJECT}}:${{github.ref_name}} -o ./image_${{inputs.PROJECT}}_${{github.ref_name}}.tar

      - name: upload
        uses: actions/upload-artifact@v3.1.2
        with:
          name: artifacts_image_${{github.ref_name}}
          path: ./image_${{inputs.PROJECT}}_${{github.ref_name}}.tar
          retention-days: 1