name: Docker Unittest
on:
  workflow_call:

jobs:
  docker-unittest:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3.5.2

      - name: conftest
        uses: docker://openpolicyagent/conftest:v0.41.0@sha256:f9e6b6739d7be0083c909196a5b4950d7b017a69038aed3ac3dd6ed0a92bfe7c
        with:
          args: test Dockerfile --all-namespaces --no-color
