name: Docker Security
on:
  workflow_call:
    inputs:
      PROJECT:
        type: string
        required: true

jobs:
  docker-security:
    runs-on: ubuntu-22.04
    steps:
      - name: download a build artifact
        uses: actions/download-artifact@v3.0.2
        id: download
        with:
          name: artifacts_image_${{github.ref_name}}

      - name: docker load
        run: docker image load --input image_${{inputs.PROJECT}}_${{github.ref_name}}.tar

      - name: docker scan
        uses: anchore/scan-action@v3.3.4
        continue-on-error: true
        with:
          image: image_${{inputs.PROJECT}}:${{github.ref_name}}
          output-format: table
