name: Docker Build
on:
  workflow_call:
    inputs:
      PROJECT:
        type: string
        required: true
      FILE:
        type: string
        default: Dockerfile
      TARGET:
        type: string
        default: null
    secrets:
      SSH_KEY:
        required: false
      BUILD_ARGS:
        required: false

jobs:
  docker-build:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.1

      - name: set up qemu
        uses: docker/setup-qemu-action@v3.0.0

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: add key to ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        if: "${{ env.SSH_KEY != ''}}"
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: build
        if: "${{ env.SSH_KEY == ''}}"
        uses: docker/build-push-action@v5.1.0
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        with:
          context: .
          file: ${{inputs.FILE}}
          push: false
          load: false
          outputs: type=docker,dest=./image_${{inputs.PROJECT}}.tar
          target: ${{inputs.TARGET}}
          build-args: ${{secrets.BUILD_ARGS}}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: image_${{inputs.PROJECT}}:gha

      - name: build
        uses: docker/build-push-action@v5.1.0
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        if: "${{ env.SSH_KEY != ''}}"
        with:
          context: .
          file: ${{inputs.FILE}}
          push: false
          load: false
          outputs: type=docker,dest=./image_${{inputs.PROJECT}}.tar
          target: ${{inputs.TARGET}}
          build-args: ${{secrets.BUILD_ARGS}}
          ssh: default
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: image_${{inputs.PROJECT}}:gha

      - name: upload
        uses: actions/upload-artifact@v4.3.0
        with:
          name: artifacts_image_${{inputs.PROJECT}}
          path: ./image_${{inputs.PROJECT}}.tar
          retention-days: 1
