name: Docker Docs
on:
  workflow_call:
    inputs:
      PROJECT:
        type: string
        required: true

jobs:
  docker-docs:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v5.0.0

      - name: download a build artifact
        uses: actions/download-artifact@v5.0.0
        id: download
        with:
          name: artifacts_image_${{inputs.PROJECT}}

      - name: docker-docs
        uses: docker://anchore/syft:v1.29.1@sha256:5bb3f3b45937489b380559f178a7bea715d574a99a1d4da56591535119dde386
        with:
          args: packages docker-archive:./image_${{inputs.PROJECT}}.tar  -o template -t "./README.md.tmpl" > README.md

      - name: commit changes
        uses: EndBug/add-and-commit@v9.1.4
        with:
          default_author: github_actions
          message: "Update Readme"
          add: "README.md"
