name: Docker Build
on:
  workflow_call:
    inputs:
      PROJECT:
        type: string
        required: true
      FILE:
        type: string
        default: Dockerfile
    secrets:
      SSH_KEY:
        required: false


jobs:
  docker-build:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.1

      - name: set up qemu
        uses: docker/setup-qemu-action@v3.0.0

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: add key to ssh-agent
        uses: webfactory/ssh-agent@v0.8.0
        if: "${{ env.SSH_KEY != ''}}"
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        with:
            ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: build
        if: "${{ env.SSH_KEY == ''}}"
        uses: docker/build-push-action@v5.0.0
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        with:
          context: .
          file: ${{inputs.FILE}}
          push: false
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: image_${{inputs.PROJECT}}:gha

      - name: build
        uses: docker/build-push-action@v5.0.0
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        if: "${{ env.SSH_KEY != ''}}"
        with:
          context: .
          file: ${{inputs.FILE}}
          push: false
          load: true
          ssh: default
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: image_${{inputs.PROJECT}}:gha

      - name: docker image save
        run: docker image save image_${{inputs.PROJECT}}:gha -o ./image_${{inputs.PROJECT}}.tar

      - name: upload
        uses: actions/upload-artifact@v3.1.3
        with:
          name: artifacts_image_${{inputs.PROJECT}}
          path: ./image_${{inputs.PROJECT}}.tar
          retention-days: 1