name: Docker Release
on:
  workflow_call:
    inputs:
      PROJECT:
        type: string
        required: true
      GCP_REGISTRY:
        type: string
        required: false
        default: "eu.gcr.io"
      DOCKER_IMAGE_TAG:
        type: string
        required: true
      GCP_PROJECT_ID:
        type: string
        required: true
    secrets:
      GCR_JSON_KEY:
        required: true

jobs:
  docker-release:
    runs-on: ubuntu-22.04
    steps:
      - name: download a build artifact
        uses: actions/download-artifact@v3.0.2
        id: download
        with:
          name: artifacts_image_${{github.ref_name}}

      - name: docker load
        run: docker image load --input image_${{inputs.PROJECT}}_${{github.ref_name}}.tar

      - name: tag image
        run: |
          docker tag image_${{inputs.PROJECT}}:${{github.ref_name}} ${{ inputs.GCP_REGISTRY }}/${{ inputs.GCP_PROJECT_ID }}/${{ inputs.PROJECT }}:${{ inputs.DOCKER_IMAGE_TAG }}
          docker image ls -a

      - name: login to gcr
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ inputs.GCP_REGISTRY }}
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}

      - name: push to registry
        run: docker push ${{ inputs.GCP_REGISTRY }}/${{ inputs.GCP_PROJECT_ID }}/${{ inputs.PROJECT }}:${{ inputs.DOCKER_IMAGE_TAG }}

