name: Docker Run
on:
  workflow_call:
    inputs:
      PROJECT:
        type: string
        required: true
      COMMAND:
        type: string
        required: true

jobs:
  docker-run:
    runs-on: ubuntu-22.04
    steps:
      - name: download a build artifact
        uses: actions/download-artifact@v4.1.2
        id: download
        with:
          name: artifacts_image_${{inputs.PROJECT}}

      - name: docker load
        run: docker image load --input image_${{inputs.PROJECT}}.tar

      - name: docker run
        id: run
        run: docker run --rm image_${{inputs.PROJECT}}:gha ${{inputs.COMMAND}}