name: Docker Unittest
on:
  workflow_call:

jobs:
  docker-unittest:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0

      - name: conftest
        uses: docker://openpolicyagent/conftest:v0.39.0@sha256:042e0b78eff667ae824f8d49a22af7a53295c7b15011d368c7fb382b22d6cb8b
        with:
          args: test Dockerfile --all-namespaces --no-color
