name: Docker Unittest
on:
  workflow_call:

jobs:
  docker-unittest:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0

      - name: conftest
        uses: docker://openpolicyagent/conftest:v0.39.2@sha256:ed13a4339535bf14bbe72be0298ff96ee9d7d5306da631766b72f99ade1f23e4
        with:
          args: test Dockerfile --all-namespaces --no-color
