name: Docker Run
on:
  workflow_call:
    inputs:
      PROJECT:
        type: string
        required: true
      COMMAND:
        type: string
        required: true

jobs:
  docker-run:
    runs-on: ubuntu-22.04
    steps:
      - name: lowercase things
        id: lowercase
        env:
          project: ${{inputs.PROJECT}}
        run: |
          echo "project=${project,,}"  >> "$GITHUB_OUTPUT"

      - name: download a build artifact
        uses: actions/download-artifact@v4.1.7
        id: download
        with:
          name: artifacts_image_${{inputs.PROJECT}}

      - name: load image
        id: image_ids
        run: |
          {
            echo 'ids<<EOF'
            docker image load --input image_${{steps.lowercase.outputs.project}}.tar | sed 's/Loaded image: //g'
            echo EOF
          } >> $GITHUB_OUTPUT

      - name: docker run
        id: run
        run: |
          TAGS="${{steps.image_ids.outputs.ids}}"
          echo "Original TAGS: $TAGS"
          TRIMMED_TAG="${TAGS%% *}"
          echo "Trimmed TAG: $TRIMMED_TAG"
          docker run --rm ${TRIMMED_TAG} ${{inputs.COMMAND}}
