name: Docker Build
on:
  workflow_call:
    inputs:
      PROJECT:
        type: string
        required: true


jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          load: true
          tags: image_${{inputs.PROJECT}}:${{GITHUB_SHA}}
      - name: docker image save
        run: docker image save image_${{inputs.PROJECT}}:${GITHUB_SHA} -o ./image_${{inputs.PROJECT}}_${GITHUB_SHA}.tar
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: artifacts_image_${GITHUB_SHA}
          path: ./image_${{inputs.PROJECT}}_${GITHUB_SHA}.tar