name: Git create PR
on:
  workflow_call:
    inputs:
      TARGET_BRANCH:
        type: string
        required: true
      TAG:
        type: string
        required: true
      RELEASE_NAME:
        type: string
        required: true
      CHANGELOG:
        type: string
        required: false
        default: "n/a"

jobs:
  git-create-pr:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2.12.1
        with:
          destination_branch: ${{inputs.TARGET_BRANCH}}
          pr_title: Promote ${{inputs.TAG}} to ${{inputs.TARGET_BRANCH}}
          pr_body: ${{inputs.RELEASE_NAME}} (${{inputs.TAG}}) wants to go ${{inputs.TARGET_BRANCH}} \
                ${{ inputs.CHANGELOG }}
