name: Git PR Sanity
on:
  workflow_call:

jobs:
  git-pr-sanity:
    runs-on: ubuntu-22.04
    steps:
      - name: Process stale PRs
        uses: Sonia-corporation/stale@2.5.0
        with:
          pull-request-days-before-close: 2555
