name: Git create Changelog
on:
  workflow_call:

jobs:
  git-tag-release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: generate changelog
        uses: orhun/git-cliff-action@v1
        id: git-cliff
        with:
          config: ./cliff.toml
      - name: write file
        run: cat ${{ steps.git-cliff.outputs.changelog }} >> ./CHANGELOG.md
      - name: commit changes
        uses: EndBug/add-and-commit@v9.1.1
        with:
          default_author: github_actions
          message: 'chore: Update Changelog'
          add: ./CHANGELOG.md