name: Git Changelog
on:
  workflow_call:

jobs:
  git-changelog:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.0

      - name: generate changelog
        uses: orhun/git-cliff-action@v2.1.1
        id: git-cliff
        with:
          config: ./cliff.toml
          args: --verbose

      - name: write file
        run: cat ${{ steps.git-cliff.outputs.changelog }} > ./CHANGELOG.md

      - name: commit changes
        uses: EndBug/add-and-commit@v9.1.3
        with:
          default_author: github_actions
          message: 'chore: Update Changelog'
          add: ./CHANGELOG.md