name: Git create PR
on:
  workflow_call:
    inputs:
      TARGET_BRANCH:
        type: string
        required: true
      TAG:
        type: string
        required: true
      RELEASE_NAME:
        type: string
        required: true
      CHANGELOG:
        type: string
        required: false
        default: "n/a"

jobs:
  git-create-pr:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3.5.2

      - name: create release branch
        run: git checkout -b release/${{inputs.TAG}} && git config user.name github-actions && git config user.email github-actions@github.com && git push --set-upstream origin release/${{inputs.TAG}}

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2.12.1
        with:
          source_branch: release/${{inputs.TAG}}
          destination_branch: ${{inputs.TARGET_BRANCH}}
          pr_title: Promote ${{inputs.TAG}} to ${{inputs.TARGET_BRANCH}}
          pr_body: |
            ${{inputs.RELEASE_NAME}} (${{inputs.TAG}}) wants to go ${{inputs.TARGET_BRANCH}}

            ${{ inputs.CHANGELOG }}
