name: Git create Changelog
on:
  workflow_call:

jobs:
  git-tag-release:
    runs-on: ubuntu-22.04
    steps:
      - name: generate changelog
        uses: orhun/git-cliff-action@v1
        id: git-cliff
        with:
          config: cliff.toml
        env:
          OUTPUT: CHANGELOG.md
      - name: commit changes
        uses: EndBug/add-and-commit@v9.1.1
        with:
          push: --force
          default_author: github_actions
          message: 'chore: Update Changelog'
          add: 'CHANGELOG.md'