name: Helm Unittest
on:
  workflow_call:


jobs:
  unittest:
    strategy:
      matrix:
        ENVIRONMENT: ["stage","live"]
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install helm
        uses: Azure/setup-helm@v3.3
        with:
          version: 3.10.0

      - name: helm template
        run: for d in ./charts/* ; do helm template $(basename -- $d) -f ${d}/_live.yaml ${d}/ > ./rendered_$(basename -- $d)_${{ matrix.ENVIRONMENT }}.yaml; done

      - name: conftest
        uses: docker://openpolicyagent/conftest:v0.35.0@sha256:95a8879ababe8be9f0369113c87436300adbc7599a0b940c4733c220b3e477c5
        with:
          args: -c 'for d in ./rendered_*; do conftest test "${d}" --all-namespaces --no-color; done'
          entrypoint: sh