name: Helm Unittest
on:
  workflow_call:

env:
  HELM_VERSION: 3.12.0

jobs:
  helm-unittest:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v5.0.0

      - name: install helm
        uses: Azure/setup-helm@v4
        with:
          version: ${{env.HELM_VERSION}}

      - name: install helm-unittest plugin
        run: helm plugin install https://github.com/helm-unittest/helm-unittest --version v1.0.3

      - name: helm unittest
        run: helm unittest ./charts/*
