name: Helm Unittest
on:
  workflow_call:

env:
  HELM_VERSION: 3.11.2

jobs:
  helm-unittest:
    strategy:
      matrix:
        ENVIRONMENT: ["stage","live"]
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0

      - name: install helm
        uses: Azure/setup-helm@v3.5
        with:
          version: ${{env.HELM_VERSION}}

      - name: helm template
        run: for d in ./charts/* ; do helm template $(basename -- $d) -f ${d}/_live.yaml ${d}/ > ./rendered_$(basename -- $d)_${{ matrix.ENVIRONMENT }}.yaml; done

      - name: conftest
        uses: docker://openpolicyagent/conftest:v0.39.2@sha256:ed13a4339535bf14bbe72be0298ff96ee9d7d5306da631766b72f99ade1f23e4
        with:
          args: -c 'for d in ./rendered_*; do conftest test "${d}" --all-namespaces --no-color; done'
          entrypoint: sh