name: Helm Security
on:
  workflow_call:

env:
  HELM_VERSION: 3.11.2

jobs:
  helm-security:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0

      - name: install helm
        uses: Azure/setup-helm@v3.5
        with:
          version: ${{env.HELM_VERSION}}

      - name: checkov
        uses: docker://bridgecrew/checkov:2.3.79@sha256:89ce8690ea86476ac974df108472fd364758d73774a21ed95856ec25eb946c1c
        with:
          entrypoint: checkov
          args: -d ./charts -o cli -o junitxml --output-file-path ./checkov.junit.xml -s

      - uses: actions/upload-artifact@v3.1.2
        with:
          name: checkov.junit.xml
          path: ./checkov.junit.xml/results_junitxml.xml
          retention-days: 1