name: Helm Security
on:
  workflow_call:

env:
  HELM_VERSION: 3.12.0

jobs:
  helm-security:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v5.0.0

      - name: install helm
        uses: Azure/setup-helm@v4
        with:
          version: ${{env.HELM_VERSION}}

      - name: checkov
        uses: docker://bridgecrew/checkov:3.2.457@sha256:021af1112246ce9f6e8ba6acfd792e40efec59d60f64ca17cf7dce7825f55975
        with:
          entrypoint: checkov
          args: -d ./charts -o cli -o junitxml --output-file-path ./checkov.junit.xml -s

      - uses: actions/upload-artifact@v5.0.0
        with:
          name: checkov.junit.xml
          path: ./checkov.junit.xml/results_junitxml.xml
          retention-days: 1
