name: PHP Lint
on:
  workflow_call:
    inputs:
      PROJECT:
        type: string
        required: true
      PATH:
        type: string
        required: false
        default: .
      COMPOSER_PATH:
        type: string
        required: false
        default: .
      COMPOSER_PHP_VERSION:
        type: string
        required: false
        default: "7.4"
      COMPOSER_VERSION:
        type: string
        required: false
        default: "1.x"
      COMPOSER_DEV:
        type: string
        required: false
        default: "no"
      COMPOSER_MEMORY_LIMIT:
        type: string
        required: false
        default: "256M"
      PHP_EXTENSIONS:
        type: string
        required: false
        default: "amqp"
      PHPCS_PATH:
        type: string
        required: false
        default: .
      PHPCS_STANDARD:
        type: string
        required: false
        default: PSR2
        description: "the coding standard to use, e.g. PSR2, PSR12, WordPress, etc., or a path to a custom standard file"
      FLAVOUR:
        type: string
        required: false
        default: phpcs
        description: "one of phpcs, phpstan"
      WORKING_DIRECTORY:
        type: string
        required: false
        default: .
      ARGS_STRING:
        type: string
        required: false
        default: "--standard=${{inputs.PHPCS_STANDARD}} ${{inputs.PHPCS_PATH}}"
      PHPSTAN_VERSION:
        type: string
        required: false
        default: "latest"
        description: "the version of PHPStan to use, e.g. 1.0, 1.1, etc."
    secrets:
      SSH_KEY:
        required: false
      SSH_KEY_PUB:
        required: false

jobs:
  php-lint:
    defaults:
      run:
        working-directory: ${{inputs.WORKING_DIRECTORY}}
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2

#      - name: Cache Composer dependencies
#        uses: actions/cache@v4.2.3
#        with:
#          path: /tmp/composer-cache
#          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
#
#      - name: directory ownership
#        run: git config --global --add safe.directory "*"

      - uses: php-actions/composer@v6.1.2
        with:
          php_version: ${{inputs.COMPOSER_PHP_VERSION}}
          version: ${{inputs.COMPOSER_VERSION}}
          args: "--ignore-platform-reqs --working-dir ${{inputs.COMPOSER_PATH}}"
          php_extensions: ${{inputs.PHP_EXTENSIONS}}
          dev: ${{inputs.COMPOSER_DEV}}
          ssh_key: ${{secrets.SSH_KEY}}
          ssh_key_pub: ${{secrets.SSH_KEY_PUB}}
          memory_limit: ${{inputs.COMPOSER_MEMORY_LIMIT}}
          working_dir: ${{inputs.COMPOSER_PATH}}

#      - uses: php-actions/phpstan@v3.0.3
#        with:
#          memory_limit: ${{inputs.COMPOSER_MEMORY_LIMIT}}
#          php_extensions: ${{inputs.PHP_EXTENSIONS}}
#          php_version: ${{inputs.COMPOSER_PHP_VERSION}}
#          vendored_phpstan_path: ${{inputs.COMPOSER_PATH}}
#          version: ${{inputs.PHPSTAN_VERSION}}
#        if: inputs.FLAVOUR == 'phpstan'

      - name: phpstan
        run: |
          which phpstan
#          vendor/bin/phpstan analyse ${{ inputs.PATH }} --memory-limit=${{ inputs.COMPOSER_MEMORY_LIMIT }} --no-progress --no-interaction --no-ansi
        if: inputs.FLAVOUR == 'phpstan'

      - name: phpcs
        uses: docker://docker.io/cytopia/phpcs:3@sha256:f1e6e93e9ce6be79e6d27c42b8cdfb7a07255275281e8db961ad3c6f0c1de5d0 # https://hub.docker.com/r/cytopia/phpcs
        with:
          args: ${{ inputs.ARGS_STRING }}
#          args: --standard=${{inputs.PHPCS_STANDARD}} ${{inputs.PHPCS_PATH}}
        if: inputs.FLAVOUR == 'phpcs'
