name: PHP Lint
on:
  workflow_call:
    inputs:
      PROJECT:
        type: string
        required: true
      PATH:
        type: string
        required: false
      COMPOSER_PHP_VERSION:
        type: string
        required: false
        default: "7.4"
      COMPOSER_VERSION:
        type: string
        required: false
        default: "1.x"
      COMPOSER_DEV:
        type: string
        required: false
        default: "no"
      COMPOSER_MEMORY_LIMIT:
        type: string
        required: false
        default: "256M"
      PHP_EXTENSIONS:
        type: string
        required: false
        default: "amqp"
      FLAVOUR:
        type: string
        required: false
        default: phpcs
        description: "one of phpcs, phpstan"
    secrets:
      SSH_KEY:
        required: false
      SSH_KEY_PUB:
        required: false



jobs:
  php-lint:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: php-actions/composer@v6
        with:
          php_version: ${{inputs.COMPOSER_PHP_VERSION}}
          version: ${{inputs.COMPOSER_VERSION}}
          args: "--ignore-platform-reqs --working-dir ${{inputs.PATH}}"
          php_extensions: ${{inputs.PHP_EXTENSIONS}}
          dev: ${{inputs.COMPOSER_DEV}}
          ssh_key: ${{secrets.SSH_KEY}}
          ssh_key_pub: ${{secrets.SSH_KEY_PUB}}
          memory_limit: ${{inputs.COMPOSER_MEMORY_LIMIT}}

      - uses: php-actions/phpstan@v3
        with:
          path: ${{inputs.PATH}}
          memory_limit: ${{inputs.COMPOSER_MEMORY_LIMIT}}
        if: ${{inputs.FLAVOUR}} == "phpstan"

      - name: PHP Code Style (phpcs)
        uses: chindit/actions-phpcs@master
        with:
          dir: ${{inputs.PATH}}
        if:  ${{inputs.FLAVOUR}} == "phpcs"