name: PHP Lint
on:
  workflow_call:
    inputs:
      PROJECT:
        type: string
        required: true
      PATH:
        type: string
        required: false
      COMPOSER_PHP_VERSION:
        type: string
        required: false
        default: "7.4"
      COMPOSER_VERSION:
        type: string
        required: false
        default: "1.x"
      FLAVOUR:
        type: string
        required: false
        default: phpcs
        description: "one of phpcs, phpstan"


jobs:
  php-lint:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: php-actions/composer@v6
        with:
          php_version: ${{inputs.COMPOSER_PHP_VERSION}}
          version: ${{inputs.COMPOSER_VERSION}}
          args: "--working-dir ${{inputs.PATH}}"

      - uses: php-actions/phpstan@v3
        with:
          path: ${{inputs.PATH}}
        if: ${{inputs.FLAVOUR}} == "phpstan"

      - name: PHP Code Style (phpcs)
        uses: chindit/actions-phpcs@master
        with:
          dir: ${{inputs.PATH}}
        if:  ${{inputs.FLAVOUR}} == "phpcs"