name: PHP Lint
on:
  workflow_call:
    inputs:
      PROJECT:
        type: string
        required: true
      PATH:
        type: string
        required: false
      COMPOSER_PHP_VERSION:
        type: number
        required: false
        default: 7.4
      COMPOSER_VERSION:
        type: string
        required: false
        default: "1.x"
      FLAVOUR:
        type: string
        required: false
        default: phpcs
        description: "one of phpcs, phpstan"


jobs:
  php-lint:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: php-actions/composer@v6
        with:
          php_version: ${{github.event.inputs.COMPOSER_PHP_VERSION}}
          version: ${{github.event.inputs.COMPOSER_VERSION}}
          args: "--working-dir ${{github.event.inputs.PATH}}"

      - uses: php-actions/phpstan@v3
        with:
          path: ${{github.event.inputs.PATH}}
        if: ${{github.event.inputs.FLAVOUR}} == "phpstan"

      - name: PHP Code Style (phpcs)
        uses: chindit/actions-phpcs@master
        with:
          dir: ${{github.event.inputs.PATH}}
        if:  ${{github.event.inputs.FLAVOUR}} == "phpcs"