name: Terraform Build
on:
  workflow_call:
    inputs:
      WORKING_DIRECTORY:
        type: string
        required: false
        default: "."
      ENVIRONMENT:
        type: string
        required: true
      USE_CUSTOM_ARTIFACTS:
        type: boolean
        default: false
        required: false
        description: "if set to true, the action will upload custom artifacts from the working directory in conjunction with the CUSTOM_ARTIFACT_PATH input"
      CUSTOM_ARTIFACT_PATH:
        type: string
        required: false
        default: ""
        description: >
          Subdirectory or file path inside the WORKING_DIRECTORY to upload as custom artifacts.
          Set this only when USE_CUSTOM_ARTIFACTS is true.
          For example, with WORKING_DIRECTORY='.' and CUSTOM_ARTIFACT_PATH='dist', files from './dist' will be uploaded.
    secrets:
      GCP_JSON_KEY:
        required: false
        description: "can be inherited by using the 'inherit' keyword https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idsecretsinherit"

env:
  TERRAFORM_VERSION: 1.13.4

concurrency:
  group: terraform-build-${{ inputs.ENVIRONMENT }}
  cancel-in-progress: false

jobs:
  terraform-build:
    defaults:
      run:
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v5.0.0

      - name: secrets-to-env
        uses: oNaiPs/secrets-to-env-action@v1.5
        with:
          secrets: ${{ toJSON(secrets) }}
          include: TF_VAR_*

      - name: install terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: ${{env.TERRAFORM_VERSION}}
          terraform_wrapper: false

      - name: authenticate to google cloud
        id: auth
        uses: google-github-actions/auth@v3.0.0
        with:
          credentials_json: "${{ secrets.GCP_JSON_KEY }}"

      - name: terraform init
        run: terraform init

      - name: terraform select workspace
        run: terraform workspace select ${{inputs.ENVIRONMENT}} || terraform workspace new ${{inputs.ENVIRONMENT}} && terraform workspace select ${{inputs.ENVIRONMENT}}

      - name: terraform plan
        run: terraform plan -var-file=_global.json -var-file=_${{inputs.ENVIRONMENT}}.json -out=plan_${{inputs.ENVIRONMENT}}_${{github.sha}}.bin

      - name: generate plan json
        run: terraform show -json -no-color plan_${{inputs.ENVIRONMENT}}_${{github.sha}}.bin > test_${{inputs.ENVIRONMENT}}_${{github.sha}}.json

      - name: inform about changes
        uses: liatrio/terraform-change-pr-commenter@v1.14.0
        with:
          json-file: ${{ inputs.WORKING_DIRECTORY }}/test_${{inputs.ENVIRONMENT}}_${{github.sha}}.json
          expand-comment: "true"
          include-plan-job-summary: "true"

      - name: upload
        uses: actions/upload-artifact@v4.6.2
        with:
          name: artifacts_${{inputs.ENVIRONMENT}}_${{github.sha}}
          path: ${{ inputs.WORKING_DIRECTORY }}/*_${{inputs.ENVIRONMENT}}_${{github.sha}}.*
          retention-days: 1

      - name: upload custom artifacts
        uses: actions/upload-artifact@v4.6.2
        if: ${{ inputs.USE_CUSTOM_ARTIFACTS == true }}
        with:
          name: custom_artifacts_${{inputs.ENVIRONMENT}}_${{github.sha}}
          path: ${{ inputs.WORKING_DIRECTORY }}/${{ inputs.CUSTOM_ARTIFACT_PATH }}
          retention-days: 1
          if-no-files-found: "warn"
