name: Terraform Build
on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        type: string
        required: true
    secrets:
      GCP_PROJECT_ID:
        required: true
      GCP_JSON_KEY:
        required: true

env:
  TERRAFORM_VERSION: 1.4.0

jobs:
  terraform-build:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0

      - name: install terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: ${{env.TERRAFORM_VERSION}}
          terraform_wrapper: false

      - name: authenticate to google cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_JSON_KEY }}'

      - name: terraform init
        run: terraform init

      - name: terraform select workspace
        run: terraform workspace select ${{inputs.ENVIRONMENT}} || terraform workspace new ${{inputs.ENVIRONMENT}} && terraform workspace select ${{inputs.ENVIRONMENT}}

      - name: terraform plan
        run: terraform plan -var-file=_global.json -var-file=_${{inputs.ENVIRONMENT}}.json -out=plan_${{inputs.ENVIRONMENT}}_${{github.sha}}.bin

      - name: generate plan json
        run: terraform show -json -no-color plan_${{inputs.ENVIRONMENT}}_${{github.sha}}.bin > test_${{inputs.ENVIRONMENT}}_${{github.sha}}.json

      - name: inform about changes
        uses: liatrio/terraform-change-pr-commenter@v1.4.1
        with:
          json-file: test_${{inputs.ENVIRONMENT}}_${{github.sha}}.json
          expand-comment: 'true'
          include-plan-job-summary: 'true'

      - name: upload
        uses: actions/upload-artifact@v3.1.2
        with:
          name: artifacts_${{inputs.ENVIRONMENT}}_${{github.sha}}
          path: ./*_${{inputs.ENVIRONMENT}}_${{github.sha}}.*
          retention-days: 1