name: Terraform Build
on:
  workflow_call:
    inputs:
      WORKING_DIRECTORY:
        type: string
        required: false
        default: "."
      ENVIRONMENT:
        type: string
        required: true
    secrets:
      GCP_JSON_KEY:
        required: false
        description: "can be inherited by using the 'inherit' keyword https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idsecretsinherit"

env:
  TERRAFORM_VERSION: 1.7.5

jobs:
  terraform-build:
    defaults:
      run:
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.5

      - name: secrets-to-env
        uses: oNaiPs/secrets-to-env-action@v1.5
        with:
          secrets: ${{ toJSON(secrets) }}
          include: TF_VAR_*

      - name: install terraform
        uses: hashicorp/setup-terraform@v3.1.1
        with:
          terraform_version: ${{env.TERRAFORM_VERSION}}
          terraform_wrapper: false

      - name: authenticate to google cloud
        id: auth
        uses: google-github-actions/auth@v2.1.2
        with:
          credentials_json: "${{ secrets.GCP_JSON_KEY }}"

      - name: terraform init
        run: terraform init

      - name: terraform select workspace
        run: terraform workspace select ${{inputs.ENVIRONMENT}} || terraform workspace new ${{inputs.ENVIRONMENT}} && terraform workspace select ${{inputs.ENVIRONMENT}}

      - name: terraform plan
        run: terraform plan -var-file=_global.json -var-file=_${{inputs.ENVIRONMENT}}.json -out=plan_${{inputs.ENVIRONMENT}}_${{github.sha}}.bin

      - name: generate plan json
        run: terraform show -json -no-color plan_${{inputs.ENVIRONMENT}}_${{github.sha}}.bin > test_${{inputs.ENVIRONMENT}}_${{github.sha}}.json

      - name: inform about changes
        uses: liatrio/terraform-change-pr-commenter@v1.4.5
        with:
          json-file: ${{ inputs.WORKING_DIRECTORY }}/test_${{inputs.ENVIRONMENT}}_${{github.sha}}.json
          expand-comment: "true"
          include-plan-job-summary: "true"

      - name: upload
        uses: actions/upload-artifact@v4.3.3
        with:
          name: artifacts_${{inputs.ENVIRONMENT}}_${{github.sha}}
          path: ${{ inputs.WORKING_DIRECTORY }}/*_${{inputs.ENVIRONMENT}}_${{github.sha}}.*
          retention-days: 1
