name: Terraform Docs
on:
  workflow_call:
    inputs:
      WORKING_DIRECTORY:
        type: string
        required: false
        default: '.'
      ENVIRONMENT:
        type: string
        required: true

jobs:
  terraform-docs:
    defaults:
      run:
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.5

      - name: terraform docs
        uses: terraform-docs/gh-actions@v1.1.0
        with:
          git-push: true
