name: Terraform Deploy Workflow

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      terraform_version:
        type: string
        required: false
        default: '1.1.4'
    secrets:
      GOOGLE_APPLICATION_CREDENTIALS:
        required: true

jobs:
  parse_issue_data:
    if: |
      github.event_name != 'pull_request' && 
      !github.event.issue.pull_request && 
      github.event.comment.body == '/approve'
    runs-on: ubuntu-20.04
    outputs:
      tag: ${{ fromJSON(steps.issue_body_parser.outputs.payload).tag }}
    steps:
      - name: Comment on Issue      
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: 'Deployment Initiated 🚀'
          
      - name: Get Issue Data
        uses: peter-murray/issue-body-parser-action@v1
        id: issue_body_parser
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_id: ${{ github.event.issue.number }}         
          payload: yaml

      - name: Remove Issue Tag
        uses: actions-ecosystem/action-remove-labels@v1
        if: ${{ startsWith(github.event.comment.body, '/approve') }}
        with:
          labels: |
            wait-for-approval

  deploy:
    runs-on: ubuntu-20.04
    needs: parse_issue_data
    if: |
      (github.event_name != 'pull_request' &&
       github.event.issue.pull_request && 
       github.event.comment.body == '/approve') || 
      (github.event_name == 'pull_request' && 
       github.event.action == 'closed' && 
       github.event.pull_request.merged == true)
    outputs:
      tag: ${{ steps.tag_version.outputs.new_tag }}
      changelog: ${{ steps.tag_version.outputs.changelog }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ inputs.terraform_version }}

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Select Workspace
        run: terraform workspace select ${{ inputs.environment }} && true || terraform workspace new ${{ inputs.environment }}

      - name: Terraform Show Workspace
        id: workspace
        run: terraform workspace show

      - name: Terraform Plan
        id: plan
        run: |
          if [[ -f _global.json ]]; then
              terraform plan \
              -var-file _global.json \
              -var-file _${{ inputs.environment }}.json \
              -no-color -lock-timeout=20s \
              -out plan_${{ inputs.environment }}.out
          else
              terraform plan \
              -var-file _${{ inputs.environment }}.json \
              -no-color -lock-timeout=20s \
              -out plan_${{ inputs.environment }}.out
          fi

      - name: Terraform Apply
        id: apply
        run: terraform apply -no-color -lock-timeout=20s plan_${{ inputs.environment }}.out

      - name: Bump version and push tag
        if: |
          github.event_name == 'push' &&
          github.ref_name == github.event.repository.default_branch
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
          create_annotated_tag: true
          custom_release_rules: hotfix:patch:Fix,fix:patch:Fix,patch:patch:Fix,bug:patch:Fix,security:patch:Security,feat:minor:Feature,feature:minor:Feature,minor:minor:Feature,breaking:major:BREAKING,break:major:BREAKING,major:major:BREAKING,stable:major:BREAKING,release:major:BREAKING

  issue_handling:
    runs-on: ubuntu-20.04
    needs: deploy
    if: always()
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download Issue Templatefile
        if: |
          github.event_name == 'push' &&
          github.ref_name == github.event.repository.default_branch
        run: curl https://raw.githubusercontent.com/t3n/github-actions/main/.github/templates/approve-deployment.md -o ./.github/approve-deployment.md

      - name: Create issue for approval
        if: |
          github.event_name == 'push' &&
          github.ref_name == github.event.repository.default_branch
        id: create_issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ needs.deploy.outputs.tag }}
          CHANGELOG: ${{ needs.deploy.outputs.changelog }}
        with:
          filename: .github/approve-deployment.md

      - name: Close Issue
        if: | 
          !github.event.issue.pull_request && 
          github.event.comment.body == '/approve'
        uses: peter-evans/close-issue@v1.0.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          comment: 'Deployment Completed ✅'
