name: Terraform Merge - Deploy

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      terraform_version:
        type: string
        required: false
        default: '1.1.4'
    secrets:
      GOOGLE_APPLICATION_CREDENTIALS:
        required: true

env:
  TF_WORKSPACE: ${{ inputs.environment }}

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository

      - uses: actions/download-artifact@v2
        with:
          name: plan_${{ inputs.environment }}.out

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ inputs.terraform_version }}

      - name: Terraform Init
        id: init
        run: terraform init -no-color

      - name: Terraform Apply
        id: apply
        run: terraform apply -no-color -lock-timeout=20s plan_${{ inputs.environment }}.out

  create_issue:
    needs: [deploy]
    if: env.TF_WORKSPACE == 'stage'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          