name: Terraform Deploy Workflow

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      terraform_version:
        type: string
        required: false
        default: '1.1.4'
    secrets:
      GOOGLE_APPLICATION_CREDENTIALS:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-20.04
    outputs:
      tag: ${{ steps.tag_version.outputs.new_tag }}
      changelog: ${{ steps.tag_version.outputs.changelog }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ inputs.terraform_version }}
          terraform_wrapper: false

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Select Workspace
        run: terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }}

      - name: Terraform Show Workspace
        id: workspace
        run: terraform workspace show

      - name: Terraform Plan
        id: plan
        run: terraform plan -var-file _${{ inputs.environment }}.json -no-color -lock-timeout=20s -out plan_${{ inputs.environment }}.out

      - name: Terraform Apply
        id: apply
        run: terraform apply -no-color -lock-timeout=20s plan_${{ inputs.environment }}.out

      - name: Bump version and push tag (stage)
        if: inputs.environment == 'stage'
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
          create_annotated_tag: true
          custom_release_rules: >
            hotfix:patch:Fix,
            fix:patch:Fix,
            patch:patch:Fix,
            bug:patch:Fix,
            security:patch:Security,
            feat:minor:Feature,
            feature:minor:Feature,
            minor:minor:Feature,
            breaking:major:BREAKING,
            break:major:BREAKING,
            major:major:BREAKING,
            stable:major:BREAKING,
            release:major:BREAKING

  create_issue:
    needs: deploy
    if: inputs.environment == 'stage'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create issue for approval
        if: inputs.environment == 'stage'
        id: create_issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ needs.deploy.outputs.tag }}
          CHANGELOG: ${{ needs.deploy.outputs.changelog }}
        with:
          filename: .github/approve-deployment.md
