name: Terraform Release
on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        type: string
        required: true

env:
  TERRAFORM_VERSION: 1.3.7

jobs:
  terraform-release:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install terraform
        uses: hashicorp/setup-terraform@v2.0.0
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: false

      - name: authenticate to google cloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'