name: Terraform Release
on:
  workflow_call:
    inputs:
      WORKING_DIRECTORY:
        type: string
        required: false
        default: '.'
      ENVIRONMENT:
        type: string
        required: true
    secrets:
      GCP_JSON_KEY:
        required: false
        description: "can be inherited by using the 'inherit' keyword https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idsecretsinherit"


env:
  TERRAFORM_VERSION: 1.6.3

jobs:
  terraform-release:
    defaults:
      run:
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.1

      - name: secrets-to-env
        uses: oNaiPs/secrets-to-env-action@v1.4
        with:
          secrets: ${{ toJSON(secrets) }}
          include: TF_VAR_*

      - name: install terraform
        uses: hashicorp/setup-terraform@v3.0.0
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: false

      - name: authenticate to google cloud
        id: auth
        uses: google-github-actions/auth@v1.2.0
        with:
          credentials_json: '${{ secrets.GCP_JSON_KEY }}'

      - name: download a build artifact
        uses: actions/download-artifact@v3.0.2
        id: download
        with:
          name: artifacts_${{inputs.ENVIRONMENT}}_${{github.sha}}
          path: ${{ inputs.WORKING_DIRECTORY }}

      - name: terraform init
        run: terraform init

      - name: terraform select workspace
        run: terraform workspace select ${{inputs.ENVIRONMENT}} || terraform workspace new ${{inputs.ENVIRONMENT}} && terraform workspace select ${{inputs.ENVIRONMENT}}

      - name: terraform apply
        run: terraform apply -auto-approve -no-color plan_${{inputs.ENVIRONMENT}}_${{github.sha}}.bin
