name: Terraform Release
on:
  workflow_call:
    inputs:
      WORKING_DIRECTORY:
        type: string
        required: false
        default: '.'
      ENVIRONMENT:
        type: string
        required: true
    secrets:
      GCP_PROJECT_ID:
        required: true
      GCP_JSON_KEY:
        required: true

defaults:
  run:
    working-directory: ${{ inputs.WORKING_DIRECTORY }}

env:
  TERRAFORM_VERSION: 1.3.8

jobs:
  terraform-release:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0

      - name: install terraform
        uses: hashicorp/setup-terraform@v2.0.0
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: false

      - name: authenticate to google cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_JSON_KEY }}'

      - name: download a build artifact
        uses: actions/download-artifact@v3.0.2
        id: download
        with:
          name: artifacts_${{inputs.ENVIRONMENT}}_${{github.sha}}

      - name: terraform init
        run: terraform init

      - name: terraform select workspace
        run: terraform workspace select ${{inputs.ENVIRONMENT}} || terraform workspace new ${{inputs.ENVIRONMENT}} && terraform workspace select ${{inputs.ENVIRONMENT}}

      - name: terraform apply
        run: terraform apply -auto-approve -no-color plan_${{inputs.ENVIRONMENT}}_${{github.sha}}.bin