name: Terraform Security
on:
  workflow_call:
    inputs:
      WORKING_DIRECTORY:
        type: string
        required: false
        default: '.'
      ENVIRONMENT:
        type: string
        required: true

jobs:
  terraform-security:
    defaults:
      run:
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
    runs-on: ubuntu-22.04
    steps:
      - name: download a build artifact
        uses: actions/download-artifact@v3.0.2
        id: download
        with:
          name: artifacts_${{inputs.ENVIRONMENT}}_${{github.sha}}
          path: ${{ inputs.WORKING_DIRECTORY }}

      - name: checkov
        uses: docker://bridgecrew/checkov:2.3.287@sha256:46c65709153873fc8e4bb35629ef490413c3ea1a8deda6b3ed58b496fc74fb55
        with:
          entrypoint: checkov
          args: -f ${{ inputs.WORKING_DIRECTORY }}/test_${{inputs.ENVIRONMENT}}_${{github.sha}}.json -o cli -o junitxml --output-file-path ${{ inputs.WORKING_DIRECTORY }}/checkov.junit.xml -s

      - uses: actions/upload-artifact@v3.1.2
        with:
          name: checkov.junit.xml
          path: ${{ inputs.WORKING_DIRECTORY }}/checkov.junit.xml/results_junitxml.xml
          retention-days: 1
