name: Terraform Security
on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        type: string
        required: true

env:
  TERRAFORM_VERSION: 1.4.0


jobs:
  terraform-security:
    runs-on: ubuntu-22.04
    steps:
      - name: download a build artifact
        uses: actions/download-artifact@v3.0.2
        id: download
        with:
          name: artifacts_${{inputs.ENVIRONMENT}}_${{github.sha}}

      - name: checkov
        uses: docker://bridgecrew/checkov:2.3.79@sha256:89ce8690ea86476ac974df108472fd364758d73774a21ed95856ec25eb946c1c
        with:
          entrypoint: checkov
          args: -f ./test_${{inputs.ENVIRONMENT}}_${{github.sha}}.json -o cli -o junitxml --output-file-path ./checkov.junit.xml -s

      - uses: actions/upload-artifact@v3.1.2
        with:
          name: checkov.junit.xml
          path: ./checkov.junit.xml/results_junitxml.xml
          retention-days: 1