name: Terraform Unittest
on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        type: string
        required: true

env:
  TERRAFORM_VERSION: 1.4.0

jobs:
  terraform-unittest:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0

      - name: download a build artifact
        uses: actions/download-artifact@v3.0.2
        id: download
        with:
          name: artifacts_${{inputs.ENVIRONMENT}}_${{github.sha}}

      - name: rename test file
        run: mv ./test_${{inputs.ENVIRONMENT}}_${{github.sha}}.json ./test_${{inputs.ENVIRONMENT}}.json

      - name: conftest
        uses: docker://openpolicyagent/conftest:v0.39.2@sha256:ed13a4339535bf14bbe72be0298ff96ee9d7d5306da631766b72f99ade1f23e4
        with:
          args: test ./test_${{inputs.ENVIRONMENT}}.json --all-namespaces --no-color



