name: Terraform Unittest
on:
  workflow_call:
    inputs:
      WORKING_DIRECTORY:
        type: string
        required: false
        default: '.'
      ENVIRONMENT:
        type: string
        required: true

env:
  TERRAFORM_VERSION: 1.4.5

jobs:
  terraform-unittest:
    defaults:
      run:
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3.5.2

      - name: download a build artifact
        uses: actions/download-artifact@v3.0.2
        id: download
        with:
          name: artifacts_${{inputs.ENVIRONMENT}}_${{github.sha}}
          path: ${{ inputs.WORKING_DIRECTORY }}

      - name: rename test file
        run: mv ./test_${{inputs.ENVIRONMENT}}_${{github.sha}}.json ./test_${{inputs.ENVIRONMENT}}.json

      - name: conftest
        uses: docker://openpolicyagent/conftest:v0.41.0@sha256:f9e6b6739d7be0083c909196a5b4950d7b017a69038aed3ac3dd6ed0a92bfe7c
        with:
          args: test ${{ inputs.WORKING_DIRECTORY }}/test_${{inputs.ENVIRONMENT}}.json --all-namespaces --no-color



