name: Terraform Unittest
on:
  workflow_call:
    inputs:
      WORKING_DIRECTORY:
        type: string
        required: false
        default: '.'
      ENVIRONMENT:
        type: string
        required: true

jobs:
  terraform-unittest:
    defaults:
      run:
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.3

      - name: download a build artifact
        uses: actions/download-artifact@v4.1.6
        id: download
        with:
          name: artifacts_${{inputs.ENVIRONMENT}}_${{github.sha}}
          path: ${{ inputs.WORKING_DIRECTORY }}

      - name: rename test file
        run: mv ./test_${{inputs.ENVIRONMENT}}_${{github.sha}}.json ./test_${{inputs.ENVIRONMENT}}.json

      - name: conftest
        uses: docker://openpolicyagent/conftest:v0.46.0@sha256:7da98fe5e8fe091193769e67a1823bfd1cfd16f682046474ce4ac81c0bd41dce
        with:
          args: test ${{ inputs.WORKING_DIRECTORY }}/test_${{inputs.ENVIRONMENT}}.json --all-namespaces --no-color -p ${{ inputs.WORKING_DIRECTORY }}/policy



