name: Terraform Validate
on:
  workflow_call:
    inputs:
      WORKING_DIRECTORY:
        type: string
        required: false
        default: "."

jobs:
  terraform-validate:
    defaults:
      run:
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v5.0.0

      - name: secrets-to-env
        uses: oNaiPs/secrets-to-env-action@v1.5
        with:
          secrets: ${{ toJSON(secrets) }}
          include: TF_VAR_*

      - name: tflint
        uses: docker://ghcr.io/terraform-linters/tflint:v0.58.1@sha256:0aedaea76dec88c8d19692986952bf80f77452ee74188866fd378375bcdd9d29
