name: Terraform Validate
on:
  workflow_call:

env:
  TERRAFORM_VERSION: 1.3.7

jobs:
  build:
    strategy:
      matrix:
        ENVIRONMENT: ["stage","live"]
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install terraform
        uses: hashicorp/setup-terraform@v2.0.0
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: false

      - name: authenticate to google cloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

      - name: terraform init
        run: terraform init

      - name: terraform select workspace
        run: terraform workspace select ${{ matrix.ENVIRONMENT }} || terraform workspace new ${{ matrix.ENVIRONMENT }} && terraform workspace select ${{ matrix.ENVIRONMENT }}

      - name: terraform plan
        run: terraform plan -var-file=_global.json -var-file=_${{ matrix.ENVIRONMENT }}.json -out=plan_${{ matrix.ENVIRONMENT }}_${GITHUB_SHA}.bin

      - name: terraform validate
        run: terraform validate

      - name: tflint
        uses: docker://ghcr.io/terraform-linters/tflint:v0.41.0@sha256:f942b96809085f6262bde51750da56fd13d2bdd098239d0e37c09a5acac2c50e
