name: Terraform Validate
on:
  workflow_call:

env:
  TERRAFORM_VERSION: 1.4.0

jobs:
  terraform-validate:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0

      - name: tflint
        uses: docker://ghcr.io/terraform-linters/tflint:v0.45.0@sha256:8f5007a878fc2af8f84c4455e4e5dbeeb6c5860b98250b286b70849276b02254
