name: Terraform Validate
on:
  workflow_call:
    inputs:
      WORKING_DIRECTORY:
        type: string
        required: false
        default: '.'

jobs:
  terraform-validate:
    defaults:
      run:
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.4

      - name: secrets-to-env
        uses: oNaiPs/secrets-to-env-action@v1.5
        with:
          secrets: ${{ toJSON(secrets) }}
          include: TF_VAR_*

      - name: tflint
        uses: docker://ghcr.io/terraform-linters/tflint:v0.49.0@sha256:3f567269172bce107ca9c05e9e91ad3ccebb6e9ab3871f4e5b80bee1ef89db60
