name: Terraform Validate
on:
  workflow_call:
    inputs:
      WORKING_DIRECTORY:
        type: string
        required: false
        default: '.'

defaults:
  run:
    working-directory: ${{ inputs.WORKING_DIRECTORY }}

env:
  TERRAFORM_VERSION: 1.4.5

jobs:
  terraform-validate:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3.5.2

      - name: tflint
        uses: docker://ghcr.io/terraform-linters/tflint:vv0.46.0@sha256:e940f26b801080546df5a8ba4629d7bc6fc47c940058774039c3cf8b1d6c6f59
