name: Terraform Validate
on:
  workflow_call:
    inputs:
      WORKING_DIRECTORY:
        type: string
        required: false
        default: '.'

jobs:
  terraform-validate:
    defaults:
      run:
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3.5.3

      - name: secrets-to-env
        uses: oNaiPs/secrets-to-env-action@v1.2
        with:
          secrets: ${{ toJSON(secrets) }}
          include: TF_VAR_*

      - name: tflint
        uses: docker://ghcr.io/terraform-linters/tflint:v0.46.1@sha256:b2dbd35ef461f73e626bde4e988a79ec715d6c1c71be7410a6a734533ba708b4
